program: train_cv.py
method: grid
metric:
  name: accuracy
  goal: maximize
parameters:
  C:
    values: [1, 2, 5, 10]
  dual:
    values: [0, 1]
  balanced:
    values: [0, 1]
  ensemble_size:
    values: [1, 2, 5, 10]
  use_scaler:
    values: [1]
  use_pairwise:
    values: [0, 1]
